# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Pod.create([
  { :name => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



PodTwitterList.create([
  { :pod_id => nil, :twitter_list_id => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



TwitterList.create([
  { :name => "Glee", :owner_screen_name => "GleeWetpaint", :list_slug => "glee-cast-crew-2", :created_at => "2012-10-10 02:06:10", :updated_at => "2012-10-10 02:06:10" },
  { :name => "American Idol", :owner_screen_name => "WetpaintTV", :list_slug => "american-idol-wetpaint", :created_at => "2012-10-10 02:06:10", :updated_at => "2012-10-10 02:06:10" }
], :without_protection => true )





